In [1]:
#Logistic Regression
#importing required files
import pandas as pd
import numpy as np
from sklearn import linear_model 
x=np.array([3.78,2.44,2.09,0.14,1.72,1.65,4.92,4.37,4.96,4.52,3.69,5.88]).reshape(-1,1)
y=np.array([0,0,0,0,0,0,1,1,1,1,1,1])
x

array([[3.78],
       [2.44],
       [2.09],
       [0.14],
       [1.72],
       [1.65],
       [4.92],
       [4.37],
       [4.96],
       [4.52],
       [3.69],
       [5.88]])

In [2]:
y

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [4]:
logr=linear_model.LogisticRegression()
logr.fit(x,y)

LogisticRegression()

In [5]:
predicted=logr.predict(np.array([3.46]).reshape(-1,1))
predicted

array([0])

In [7]:
#Classification model using decision tree
import sys
import matplotlib
matplotlib.use('Agg')
import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
df=pd.read_csv("DTree.csv")
print(df)

    Age  Experience  Rank Nationality   Go
0    36          10     9          UK   NO
1    42          12     4         USA   NO
2    23           4     6           N   NO
3    52           4     4         USA   NO
4    43          21     8         USA  YES
5    44          14     5          UK   NO
6    66           3     7           N  YES
7    35          14     9          UK  YES
8    52          13     7           N  YES
9    35           5     9           N  YES
10   24           3     5         USA   NO
11   18           3     7          UK  YES
12   45           9     9          UK  YES


In [8]:
d={'UK':0,'USA':1,'N':2}
d={'YES':1,'NO':0}
df['Go']=df['Go'].map(d)
print(df)

    Age  Experience  Rank Nationality  Go
0    36          10     9          UK   0
1    42          12     4         USA   0
2    23           4     6           N   0
3    52           4     4         USA   0
4    43          21     8         USA   1
5    44          14     5          UK   0
6    66           3     7           N   1
7    35          14     9          UK   1
8    52          13     7           N   1
9    35           5     9           N   1
10   24           3     5         USA   0
11   18           3     7          UK   1
12   45           9     9          UK   1


In [9]:
features=['Age','Experience','Rank','Nationality']
x=df[features]
y=df['Go']
x

Age  Experience  Rank Nationality
0    36          10     9          UK
1    42          12     4         USA
2    23           4     6           N
3    52           4     4         USA
4    43          21     8         USA
5    44          14     5          UK
6    66           3     7           N
7    35          14     9          UK
8    52          13     7           N
9    35           5     9           N
10   24           3     5         USA
11   18           3     7          UK
12   45           9     9          UK

In [10]:
features=['Age','Experience','Rank','Nationality']
x=df[features]
y=df['Go']
y

0     0
1     0
2     0
3     0
4     1
5     0
6     1
7     1
8     1
9     1
10    0
11    1
12    1
Name: Go, dtype: int64

In [21]:
# Importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


In [22]:
# Load the dataset (replace this with your own dataset)
# For demonstration, let's use the famous Iris dataset
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target


In [23]:
# Preprocess the data (scaling for better performance of some algorithms)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [24]:
# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)



In [25]:
# Define a function to train and evaluate a model
def train_and_evaluate_model(model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    return accuracy, precision, recall, f1



In [26]:
# Initialize classification algorithms
logistic_regression = LogisticRegression()
decision_tree = DecisionTreeClassifier()
random_forest = RandomForestClassifier()
svm = SVC()


In [27]:
# Train and evaluate each model
models = {
    "Logistic Regression": logistic_regression,
    "Decision Tree": decision_tree,
    "Random Forest": random_forest,
    "Support Vector Machine": svm
}

results = {}
for name, model in models.items():
    accuracy, precision, recall, f1 = train_and_evaluate_model(model)
    results[name] = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1
    }


In [28]:
# Display the results
results_df = pd.DataFrame.from_dict(results, orient='index')
print(results_df)

                        Accuracy  Precision  Recall  F1-score
Logistic Regression          1.0        1.0     1.0       1.0
Decision Tree                1.0        1.0     1.0       1.0
Random Forest                1.0        1.0     1.0       1.0
Support Vector Machine       1.0        1.0     1.0       1.0
